//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicB0t.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class UserApp : global::System.Configuration.ApplicationSettingsBase {
        
        private static UserApp defaultInstance = ((UserApp)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserApp())));
        
        public static UserApp Default {
            get {
                return defaultInstance;
            }
        }
    }
}
